-- ============================================================
-- Este archivo ya no es necesario.
-- Los índices de rendimiento están incluidos en pos.sql.
-- ============================================================
--
-- Si actualizás desde una versión anterior, podés ejecutar las
-- sentencias siguientes manualmente desde phpMyAdmin o desde la
-- consola MySQL. Son idempotentes: si el índice ya existe, MySQL
-- devolverá un error que podés ignorar.
--
-- ALTER TABLE `productos` ADD INDEX `idx_productos_id_categoria` (`id_categoria`);
-- ALTER TABLE `productos` ADD INDEX `idx_productos_codigo` (`codigo`(50));
-- ALTER TABLE `productos` ADD INDEX `idx_productos_descripcion` (`descripcion`(100));
-- ALTER TABLE `clientes` ADD INDEX `idx_clientes_documento` (`documento`);
-- ALTER TABLE `clientes` ADD INDEX `idx_clientes_nombre` (`nombre`(100));
-- ALTER TABLE `usuarios` ADD INDEX `idx_usuarios_usuario` (`usuario`(100));
-- ALTER TABLE `ventas` ADD INDEX `idx_ventas_codigo` (`codigo`);
-- ALTER TABLE `ventas` ADD INDEX `idx_ventas_id_cliente` (`id_cliente`);
-- ALTER TABLE `ventas` ADD INDEX `idx_ventas_id_vendedor` (`id_vendedor`);
-- ALTER TABLE `ventas` ADD INDEX `idx_ventas_fecha` (`fecha`);
